# Generated by Django 5.1.7 on 2025-03-22 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('año', models.PositiveIntegerField()),
                ('genero', models.CharField(choices=[('ACC', 'Acción'), ('DRM', 'Drama'), ('CMD', 'Comedia')], max_length=3)),
                ('director', models.CharField(max_length=100)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('portada', models.ImageField(blank=True, null=True, upload_to='portadas/')),
            ],
        ),
    ]
